theme: jekyll-theme-hacker

<audio controls autostart="true">
  <source src="horse.ogg" type="audio/ogg">
  <source src="horse.mp3" type="audio/mpeg">
Your browser does not support the audio element.
</audio>

background-image: url('https://github.com/Chienoki/Katusha02/blob/master/bg1.png') no-repeat;
